platforms:
  - targetPlatform: StandaloneWindows64
    runsOn: self-hosted

  - targetPlatform: StandaloneLinux64
    runsOn: self-hosted

  - targetPlatform: StandaloneOSX
    runsOn: self-hosted

  - targetPlatform: iOS
    runsOn: self-hosted

  - targetPlatform: Android
    runsOn: self-hosted

# You can add extra options per platform later, for example:
#  - targetPlatform: WebGL
#    runsOn: ubuntu-latest
#    enabled: true
#    unityBuilderCustomParameters: "-someFlag value"
#    artifactSuffix: "experimental"
