platforms:
# Windows is only actived for prevent Github Bandwith LFS
  - targetPlatform: StandaloneWindows64
    runsOn: ubuntu-latest

#  - targetPlatform: StandaloneLinux64
#    runsOn: ubuntu-latest

#  - targetPlatform: StandaloneOSX
#    runsOn: ubuntu-latest

#  - targetPlatform: iOS
#    runsOn: ubuntu-latest

#  - targetPlatform: Android
#    runsOn: ubuntu-latest

# You can add extra options per platform later, for example:
#  - targetPlatform: WebGL
#    runsOn: ubuntu-latest
#    enabled: true
#    unityBuilderCustomParameters: "-someFlag value"
#    artifactSuffix: "experimental"
